### PR TITLE
Port to GNOME Shell 45

### PR DESCRIPTION
**Pull request by justperfection**
- Only use 45 in version (45 extensions are not backward compatible).
- Ported prefs to LibAdwaita.
- Use ESM for all modules (GNOME Shell 45 Moved to ESM).
- Remove debug metadata (GNOME Shell offers `console.debug` which can be enabled on debug mode).
- Bump version.

### CODE REVIEW

**Comment by justperfection** [comment]
Hey Jimmy, this is tested on 45.rc.

Removed debug from metadata but in case you want to enable the debug mode:

```js
GLib.log_set_debug_enabled(true);
```

**Comment by amivaleo** [comment]
I feel like I should leave this extension behind... Or give it to you, maybe? 🤔

Thank you!
Apologies for taking some time to reply. I had to travel for work and couldn't find some spare time to deal with this.
I tested the extension. Everything's fine. :)

**Comment by justperfection** [comment]
Why? You don't run GNOME Shell anymore?
Well, I ported this one since I knew you don't like the port process.

**Comment by amivaleo** [comment]
> Why? You don't run GNOME Shell anymore? Well, I ported this one since I knew you don't like the port process.

No, no, I still use gnome. I've never dedicated the right time in understanding gnome extensions...

**Comment by justperfection** [comment]
Well, whenever you don't have time, just create an issue and ping me on it.

btw, we have [the port guide](https://gjs.guide/extensions/#porting-guides) on each release if you wanna diy.

**Pull request merged**
